#!/bin/bash

# Tailscale installation and configuration script
# Docker Swarm worker node setup
# Generated by Pulumi for EC2 instance

# === set hostame ===
hostnamectl set-hostname {HOSTNAME}

# Redirect all output to log file for debugging
exec > >(tee /var/log/tailscale-install.log) 2>&1

# ====== Tailscale logic ======
echo "=== Starting Tailscale installation ==="
echo "Timestamp: $(date)"
echo "Instance hostname: $(hostname)"

# Update system packages
echo "Updating system packages..."
apt-get update -y

# Install curl if not present
if ! command -v curl &> /dev/null; then
    echo "Installing curl..."
    apt-get install -y curl
fi

# Download and install Tailscale
echo "Downloading and installing Tailscale..."
curl -fsSL https://tailscale.com/install.sh | sh

# Check if Tailscale was installed successfully
if ! command -v tailscale &> /dev/null; then
    echo "ERROR: Tailscale installation failed"
    exit 1
fi

echo "Tailscale installed successfully"

# Start Tailscale service
echo "Starting Tailscale service..."
systemctl enable tailscaled
systemctl start tailscaled

# Wait for service to be ready
sleep 5

# Connect to Tailscale network
echo "Connecting to Tailscale network..."
echo "Running: tailscale up {TAILSCALE_CMD_OPTIONS}"

# Note: We don't echo the actual auth key for security
tailscale up {TAILSCALE_CMD_OPTIONS}

# Check connection status
echo "Checking Tailscale status..."
sleep 3
tailscale status

# Get Tailscale IP
echo "Tailscale IP addresses:"
tailscale ip -4
tailscale ip -6

echo "=== Tailscale installation completed ==="
echo "Check status with: sudo tailscale status"
echo "View logs with: sudo journalctl -u tailscaled"